### ISSUE TITLE
填好几个订阅后，有两个显示正常 ，但是有一个的名字显示undefined

### ISSUE THREAD

**Issue by tonygrooy** [cc63/Surge#1]
填好几个订阅后，有两个显示正常 ，但是有一个的名字显示undefined,  另外 这个图标咋定义

**Comment by cc63** [comment]
比较完整的填写范例是这样的
一号机场 = type=generic,timeout=5,script-path=https://raw.githubusercontent.com/cc63/Surge/main/Module/Panel/Sub-info/Moore/Sub-info.js,script-update-interval=86400,argument=url=订阅链接&title=标题名字&reset_day=重置日期&icon=hare&color=#0EBC06

&title=标题名字 里是控制标题中的名字的
&icon=hare&color=#0EBC06 这里是控制icon图标样式与颜色的，icon安装苹果SF Symbol的图标名称填写

**Comment by cc63** [comment]
多个订阅的话要确保这里一一对应
![IMG_2808](https://github.com/cc63/Surge/assets/99179360/f43674bd-b7c1-406b-b8f0-cfb459bf1cb7)
